// DuckHookV4 event handlers. Generated by gen_subgraphs.py; edit the generator, not this file.
import {
  BuybackBurned,
  CTOApplied,
  CTOApproved,
  CTOFeeSet,
  CTORejected,
  FeeSplitsUpdated,
  FeesClaimed,
  HolderRewardSkipped,
  LauncherAdded,
  LauncherRemoved,
  OracleDisabledSet,
  OraclePausedSet,
  OwnershipTransferred,
  PlatformWalletSet,
  PoolRegistered,
  StateViewSet,
  VaultCutSkipped,
  WethSet,
} from "../generated/DuckHookV4/DuckHookV4";
import { Bytes } from "@graphprotocol/graph-ts";
import { PoolRegistration, HookFeeClaim, CTOEvent, HookBuybackBurn, Token } from "../generated/schema";
import { eventId } from "./admin";
import { logAdminEvent, boolToString } from "./admin";

const CONTRACT = "DuckHookV4";

function tokenForPool(poolId: Bytes): Bytes | null {
  let reg = PoolRegistration.load(poolId);
  if (reg == null) return null;
  return reg.token;
}

export function handlePoolRegistered(event: PoolRegistered): void {
  let p = new PoolRegistration(event.params.poolId);
  p.poolId = event.params.poolId;
  p.token = event.params.token;
  p.creator = event.params.creator;
  p.hook = event.address;
  p.hookFeeBps = event.params.hookFeeBps;
  p.blockNumber = event.block.number;
  p.timestamp = event.block.timestamp;
  p.txHash = event.transaction.hash;
  p.save();

  // Bonding-curve tokens reach this on migration and crowdfund tokens on success, so this is where
  // they learn their pool. Launcher tokens register before their Token exists; TokenLaunched covers them.
  let t = Token.load(event.params.token);
  if (t == null) return;
  t.hasPool = true;
  t.poolId = event.params.poolId;
  t.hook = event.address;
  t.hookFeeBps = event.params.hookFeeBps;
  t.save();
}

export function handleFeesClaimed(event: FeesClaimed): void {
  let f = new HookFeeClaim(eventId(event));
  f.poolId = event.params.poolId;
  f.token = tokenForPool(event.params.poolId);
  f.amount = event.params.amount;
  f.blockNumber = event.block.number;
  f.timestamp = event.block.timestamp;
  f.txHash = event.transaction.hash;
  f.save();
}

export function handleCTOApplied(event: CTOApplied): void {
  let c = new CTOEvent(eventId(event));
  c.type = "Applied";
  c.poolId = event.params.poolId;
  c.token = tokenForPool(event.params.poolId);
  c.applicant = event.params.applicant;
  c.newCreator = event.params.newCreator;
  c.paid = event.params.paid;
  c.blockNumber = event.block.number;
  c.timestamp = event.block.timestamp;
  c.txHash = event.transaction.hash;
  c.save();
}

export function handleCTOApproved(event: CTOApproved): void {
  let tokenId = tokenForPool(event.params.poolId);
  let c = new CTOEvent(eventId(event));
  c.type = "Approved";
  c.poolId = event.params.poolId;
  c.token = tokenId;
  c.newCreator = event.params.newCreator;
  c.blockNumber = event.block.number;
  c.timestamp = event.block.timestamp;
  c.txHash = event.transaction.hash;
  c.save();

  if (tokenId === null) return;
  let t = Token.load(tokenId as Bytes);
  if (t == null) return;
  t.creator = event.params.newCreator;
  t.save();
}

export function handleCTORejected(event: CTORejected): void {
  let c = new CTOEvent(eventId(event));
  c.type = "Rejected";
  c.poolId = event.params.poolId;
  c.token = tokenForPool(event.params.poolId);
  c.applicant = event.params.applicant;
  c.blockNumber = event.block.number;
  c.timestamp = event.block.timestamp;
  c.txHash = event.transaction.hash;
  c.save();
}

export function handleBuybackBurned(event: BuybackBurned): void {
  let b = new HookBuybackBurn(eventId(event));
  b.poolId = event.params.poolId;
  b.token = tokenForPool(event.params.poolId);
  b.quoteSpent = event.params.quoteSpent;
  b.tokensBurned = event.params.tokensBurned;
  b.blockNumber = event.block.number;
  b.timestamp = event.block.timestamp;
  b.txHash = event.transaction.hash;
  b.save();
}

// ---- config and admin events, recorded as AdminEvent ----

export function handleCTOFeeSet(event: CTOFeeSet): void {
  logAdminEvent(event, CONTRACT, "CTOFeeSet", event.params.fee.toString());
}

export function handleFeeSplitsUpdated(event: FeeSplitsUpdated): void {
  logAdminEvent(event, CONTRACT, "FeeSplitsUpdated", event.params.poolId.toHexString(), event.params.splits.length.toString());
}

export function handleHolderRewardSkipped(event: HolderRewardSkipped): void {
  logAdminEvent(event, CONTRACT, "HolderRewardSkipped", event.params.poolId.toHexString(), event.params.amount.toString());
}

export function handleLauncherAdded(event: LauncherAdded): void {
  logAdminEvent(event, CONTRACT, "LauncherAdded", event.params.launcher.toHexString());
}

export function handleLauncherRemoved(event: LauncherRemoved): void {
  logAdminEvent(event, CONTRACT, "LauncherRemoved", event.params.launcher.toHexString());
}

export function handleOracleDisabledSet(event: OracleDisabledSet): void {
  logAdminEvent(event, CONTRACT, "OracleDisabledSet", event.params.poolId.toHexString(), boolToString(event.params.disabled));
}

export function handleOraclePausedSet(event: OraclePausedSet): void {
  logAdminEvent(event, CONTRACT, "OraclePausedSet", boolToString(event.params.paused));
}

export function handleOwnershipTransferred(event: OwnershipTransferred): void {
  logAdminEvent(event, CONTRACT, "OwnershipTransferred", event.params.previousOwner.toHexString(), event.params.newOwner.toHexString());
}

export function handlePlatformWalletSet(event: PlatformWalletSet): void {
  logAdminEvent(event, CONTRACT, "PlatformWalletSet", event.params.wallet.toHexString());
}

export function handleStateViewSet(event: StateViewSet): void {
  logAdminEvent(event, CONTRACT, "StateViewSet", event.params.stateView.toHexString());
}

export function handleVaultCutSkipped(event: VaultCutSkipped): void {
  logAdminEvent(event, CONTRACT, "VaultCutSkipped", event.params.poolId.toHexString(), event.params.amount.toString());
}

export function handleWethSet(event: WethSet): void {
  logAdminEvent(event, CONTRACT, "WethSet", event.params.weth.toHexString());
}
