// DuckToken event handlers. Generated by gen_subgraphs.py; edit the generator, not this file.
import {
  Approval,
  DelegateChanged,
  DelegateVotesChanged,
  DistributionRoundClosed,
  DistributionRoundFinished,
  EIP712DomainChanged,
  HolderRewardDeposited,
  HolderRewardPaid,
  Initialized,
  MetaURISet,
  OwnershipTransferred,
  RewardConfigSet,
  Transfer,
  VaultSet,
} from "../generated/templates/DuckToken/DuckToken";
import { Address, BigInt } from "@graphprotocol/graph-ts";
import { Holder, Token, HolderRewardDeposit, HolderRewardRound, HolderRewardPayout } from "../generated/schema";
import { eventId } from "./admin";

const DEAD = Address.fromString("0x000000000000000000000000000000000000dEaD");
import { logAdminEvent, boolToString } from "./admin";

const CONTRACT = "DuckToken";

function loadHolder(token: Address, account: Address): Holder {
  let id = token.toHexString() + "-" + account.toHexString();
  let h = Holder.load(id);
  if (h == null) {
    h = new Holder(id);
    h.token = token;
    h.account = account;
    h.balance = BigInt.zero();
  }
  return h as Holder;
}

function adjustHolderCount(token: Address, delta: i32): void {
  let t = Token.load(token);
  if (t == null) return;
  t.holderCount = t.holderCount + delta;
  t.save();
}

export function handleTransfer(event: Transfer): void {
  let token = event.address;

  if (event.params.from.notEqual(Address.zero())) {
    let from = loadHolder(token, event.params.from);
    let had = from.balance.gt(BigInt.zero());
    from.balance = from.balance.minus(event.params.value);
    from.updatedAt = event.block.timestamp;
    from.updatedAtBlock = event.block.number;
    from.save();
    if (had && from.balance.isZero() && event.params.from.notEqual(DEAD)) adjustHolderCount(token, -1);
  }

  if (event.params.to.notEqual(Address.zero())) {
    let to = loadHolder(token, event.params.to);
    let had = to.balance.gt(BigInt.zero());
    to.balance = to.balance.plus(event.params.value);
    to.updatedAt = event.block.timestamp;
    to.updatedAtBlock = event.block.number;
    to.save();
    // The burn address holds burned supply; it is not a holder.
    if (!had && to.balance.gt(BigInt.zero()) && event.params.to.notEqual(DEAD)) adjustHolderCount(token, 1);
  }

  if (event.params.to.equals(DEAD)) {
    let t = Token.load(token);
    if (t != null) {
      t.burnedSupply = t.burnedSupply.plus(event.params.value);
      t.save();
    }
  }
}

export function handleMetaURISet(event: MetaURISet): void {
  let t = Token.load(event.address);
  if (t == null) return;
  t.metaUri = event.params.uri;
  t.save();
}

export function handleRewardConfigSet(event: RewardConfigSet): void {
  let t = Token.load(event.address);
  if (t == null) return;
  t.rewardHook = event.params.hook;
  t.rewardCurrency = event.params.currency;
  t.save();
}

export function handleHolderRewardDeposited(event: HolderRewardDeposited): void {
  let d = new HolderRewardDeposit(eventId(event));
  d.token = event.address;
  d.amount = event.params.amount;
  d.blockNumber = event.block.number;
  d.timestamp = event.block.timestamp;
  d.txHash = event.transaction.hash;
  d.save();
}

function roundId(token: Address, roundStart: BigInt): string {
  return token.toHexString() + "-" + roundStart.toString();
}

export function handleDistributionRoundClosed(event: DistributionRoundClosed): void {
  let r = new HolderRewardRound(roundId(event.address, event.params.roundStart));
  r.token = event.address;
  r.roundStart = event.params.roundStart;
  r.pool = event.params.pool;
  r.eligibleCount = event.params.eligibleCount;
  r.totalWeight = event.params.totalWeight;
  r.finished = false;
  r.totalPaid = BigInt.zero();
  r.closedAtBlock = event.block.number;
  r.closedAtTimestamp = event.block.timestamp;
  r.closedAtTx = event.transaction.hash;
  r.save();

  let t = Token.load(event.address);
  if (t == null) return;
  t.activeRewardRound = r.id;
  t.save();
}

// Payouts are paid in batches between a round's close and finish, so they belong to the token's
// active round.
export function handleHolderRewardPaid(event: HolderRewardPaid): void {
  let p = new HolderRewardPayout(eventId(event));
  p.token = event.address;
  p.account = event.params.account;
  p.amount = event.params.amount;
  p.blockNumber = event.block.number;
  p.timestamp = event.block.timestamp;
  p.txHash = event.transaction.hash;

  let t = Token.load(event.address);
  if (t != null) {
    let active = t.activeRewardRound;
    if (active !== null) {
      let r = HolderRewardRound.load(active as string);
      if (r != null) {
        p.round = r.id;
        r.totalPaid = r.totalPaid.plus(event.params.amount);
        r.save();
      }
    }
  }
  p.save();
}

export function handleDistributionRoundFinished(event: DistributionRoundFinished): void {
  let r = HolderRewardRound.load(roundId(event.address, event.params.roundStart));
  if (r != null) {
    r.finished = true;
    r.finishedAtBlock = event.block.number;
    r.finishedAtTimestamp = event.block.timestamp;
    r.finishedAtTx = event.transaction.hash;
    r.save();
  }
  let t = Token.load(event.address);
  if (t == null) return;
  t.activeRewardRound = null;
  t.save();
}

// ---- config and admin events, recorded as AdminEvent ----

export function handleApproval(event: Approval): void {
  logAdminEvent(event, CONTRACT, "Approval", event.params.owner.toHexString(), event.params.spender.toHexString(), event.params.value.toString());
}

export function handleDelegateChanged(event: DelegateChanged): void {
  logAdminEvent(event, CONTRACT, "DelegateChanged", event.params.delegator.toHexString(), event.params.fromDelegate.toHexString(), event.params.toDelegate.toHexString());
}

export function handleDelegateVotesChanged(event: DelegateVotesChanged): void {
  logAdminEvent(event, CONTRACT, "DelegateVotesChanged", event.params.delegate.toHexString(), event.params.previousVotes.toString(), event.params.newVotes.toString());
}

export function handleEIP712DomainChanged(event: EIP712DomainChanged): void {
  logAdminEvent(event, CONTRACT, "EIP712DomainChanged");
}

export function handleInitialized(event: Initialized): void {
  logAdminEvent(event, CONTRACT, "Initialized", event.params.version.toString());
}

export function handleOwnershipTransferred(event: OwnershipTransferred): void {
  logAdminEvent(event, CONTRACT, "OwnershipTransferred", event.params.previousOwner.toHexString(), event.params.newOwner.toHexString());
}

export function handleVaultSet(event: VaultSet): void {
  logAdminEvent(event, CONTRACT, "VaultSet", event.params.vault.toHexString());
}
