// DuckLauncher event handlers. Generated by gen_subgraphs.py; edit the generator, not this file.
import {
  DexAdded,
  DexDisabled,
  ERC20Rescued,
  ETHRescued,
  Initialized,
  InstantBuySkipped,
  LaunchFeeSet,
  OwnershipTransferStarted,
  OwnershipTransferred,
  PlatformTokenSet,
  PlatformWalletSet,
  QuoteTokenAdded,
  QuoteTokenDisabled,
  RouteSucceeded,
  RoutesSet,
  TokenImplSet,
  TokenLaunched,
  UniversalRouterUpdated,
  Upgraded,
  VaultFactorySet,
} from "../generated/DuckLauncher/DuckLauncher";
import { Launch, PoolRegistration } from "../generated/schema";
import { DuckToken as DuckTokenTemplate } from "../generated/templates";
import { newToken } from "./token-meta";
import { logAdminEvent, boolToString } from "./admin";

const CONTRACT = "DuckLauncher";

export function handleTokenLaunched(event: TokenLaunched): void {
  let t = newToken(event.params.token, "Launcher", event.params.creator, event.params.quoteToken, event);
  t.hasPool = true;
  t.poolId = event.params.poolId;
  t.hook = event.params.hook;
  t.positionManager = event.params.positionManager;
  // The hook registers the pool earlier in this same transaction, before this Token existed.
  let reg = PoolRegistration.load(event.params.poolId);
  if (reg != null) t.hookFeeBps = reg.hookFeeBps;
  t.save();

  let l = new Launch(event.params.token);
  l.token = event.params.token;
  l.creator = event.params.creator;
  l.positionManager = event.params.positionManager;
  l.quoteToken = event.params.quoteToken;
  l.hook = event.params.hook;
  l.poolId = event.params.poolId;
  l.blockNumber = event.block.number;
  l.timestamp = event.block.timestamp;
  l.txHash = event.transaction.hash;
  l.save();

  DuckTokenTemplate.create(event.params.token);
}

// ---- config and admin events, recorded as AdminEvent ----

export function handleDexAdded(event: DexAdded): void {
  logAdminEvent(event, CONTRACT, "DexAdded", event.params.positionManager.toHexString(), event.params.singleton.toHexString(), event.params.hook.toHexString());
}

export function handleDexDisabled(event: DexDisabled): void {
  logAdminEvent(event, CONTRACT, "DexDisabled", event.params.positionManager.toHexString());
}

export function handleERC20Rescued(event: ERC20Rescued): void {
  logAdminEvent(event, CONTRACT, "ERC20Rescued", event.params.token.toHexString(), event.params.to.toHexString(), event.params.amount.toString());
}

export function handleETHRescued(event: ETHRescued): void {
  logAdminEvent(event, CONTRACT, "ETHRescued", event.params.to.toHexString(), event.params.amount.toString());
}

export function handleInitialized(event: Initialized): void {
  logAdminEvent(event, CONTRACT, "Initialized", event.params.version.toString());
}

export function handleInstantBuySkipped(event: InstantBuySkipped): void {
  logAdminEvent(event, CONTRACT, "InstantBuySkipped", event.params.token.toHexString(), event.params.refundedWei.toString());
}

export function handleLaunchFeeSet(event: LaunchFeeSet): void {
  logAdminEvent(event, CONTRACT, "LaunchFeeSet", event.params.fee.toString());
}

export function handleOwnershipTransferStarted(event: OwnershipTransferStarted): void {
  logAdminEvent(event, CONTRACT, "OwnershipTransferStarted", event.params.previousOwner.toHexString(), event.params.newOwner.toHexString());
}

export function handleOwnershipTransferred(event: OwnershipTransferred): void {
  logAdminEvent(event, CONTRACT, "OwnershipTransferred", event.params.previousOwner.toHexString(), event.params.newOwner.toHexString());
}

export function handlePlatformTokenSet(event: PlatformTokenSet): void {
  logAdminEvent(event, CONTRACT, "PlatformTokenSet", event.params.token.toHexString());
}

export function handlePlatformWalletSet(event: PlatformWalletSet): void {
  logAdminEvent(event, CONTRACT, "PlatformWalletSet", event.params.wallet.toHexString());
}

export function handleQuoteTokenAdded(event: QuoteTokenAdded): void {
  logAdminEvent(event, CONTRACT, "QuoteTokenAdded", event.params.token.toHexString());
}

export function handleQuoteTokenDisabled(event: QuoteTokenDisabled): void {
  logAdminEvent(event, CONTRACT, "QuoteTokenDisabled", event.params.token.toHexString());
}

export function handleRouteSucceeded(event: RouteSucceeded): void {
  logAdminEvent(event, CONTRACT, "RouteSucceeded", event.params.quoteToken.toHexString(), event.params.routeIndex.toString(), event.params.amountOut.toString());
}

export function handleRoutesSet(event: RoutesSet): void {
  logAdminEvent(event, CONTRACT, "RoutesSet", event.params.quoteToken.toHexString(), event.params.count.toString());
}

export function handleTokenImplSet(event: TokenImplSet): void {
  logAdminEvent(event, CONTRACT, "TokenImplSet", event.params.tokenImpl.toHexString());
}

export function handleUniversalRouterUpdated(event: UniversalRouterUpdated): void {
  logAdminEvent(event, CONTRACT, "UniversalRouterUpdated", event.params.router.toHexString());
}

export function handleUpgraded(event: Upgraded): void {
  logAdminEvent(event, CONTRACT, "Upgraded", event.params.implementation.toHexString());
}

export function handleVaultFactorySet(event: VaultFactorySet): void {
  logAdminEvent(event, CONTRACT, "VaultFactorySet", event.params.vaultFactory.toHexString());
}
