// DuckVault event handlers. Generated by gen_subgraphs.py; edit the generator, not this file.
import {
  BadDebtRealized,
  Borrowed,
  BuybackExecuted,
  BuybackQueued,
  CollateralAdded,
  CollateralWithdrawn,
  CreatorSet,
  Deposited,
  Enabled,
  GovernorSet,
  Initialized,
  Liquidated,
  PoolLinked,
  Repaid,
  RouteSucceeded,
  RoutesSet,
  UniversalRouterUpdated,
  Upgraded,
  Withdrawn,
} from "../generated/templates/DuckVault/DuckVault";
import { Vault, VaultDeposit, VaultBorrow, VaultRepayment, VaultCollateralChange, VaultLiquidation, VaultBadDebt, VaultBuybackQueued, VaultBuybackExecuted, VaultWithdrawal } from "../generated/schema";
import { eventId } from "./admin";
import { logAdminEvent, boolToString } from "./admin";

const CONTRACT = "DuckVault";

export function handleDeposited(event: Deposited): void {
  let d = new VaultDeposit(eventId(event));
  d.vault = event.address;
  d.from = event.params.from;
  d.amount = event.params.amount;
  d.blockNumber = event.block.number;
  d.timestamp = event.block.timestamp;
  d.txHash = event.transaction.hash;
  d.save();
}

export function handleBorrowed(event: Borrowed): void {
  let b = new VaultBorrow(eventId(event));
  b.vault = event.address;
  b.borrower = event.params.borrower;
  b.amount = event.params.amount;
  b.newDebt = event.params.newDebt;
  b.blockNumber = event.block.number;
  b.timestamp = event.block.timestamp;
  b.txHash = event.transaction.hash;
  b.save();
}

export function handleRepaid(event: Repaid): void {
  let r = new VaultRepayment(eventId(event));
  r.vault = event.address;
  r.borrower = event.params.borrower;
  r.amount = event.params.amount;
  r.remainingDebt = event.params.remainingDebt;
  r.blockNumber = event.block.number;
  r.timestamp = event.block.timestamp;
  r.txHash = event.transaction.hash;
  r.save();
}

export function handleCollateralAdded(event: CollateralAdded): void {
  let c = new VaultCollateralChange(eventId(event));
  c.vault = event.address;
  c.borrower = event.params.borrower;
  c.isAdd = true;
  c.amount = event.params.amount;
  c.blockNumber = event.block.number;
  c.timestamp = event.block.timestamp;
  c.txHash = event.transaction.hash;
  c.save();
}

export function handleCollateralWithdrawn(event: CollateralWithdrawn): void {
  let c = new VaultCollateralChange(eventId(event));
  c.vault = event.address;
  c.borrower = event.params.borrower;
  c.isAdd = false;
  c.amount = event.params.amount;
  c.blockNumber = event.block.number;
  c.timestamp = event.block.timestamp;
  c.txHash = event.transaction.hash;
  c.save();
}

export function handleLiquidated(event: Liquidated): void {
  let l = new VaultLiquidation(eventId(event));
  l.vault = event.address;
  l.borrower = event.params.borrower;
  l.liquidator = event.params.liquidator;
  l.repaid = event.params.repaid;
  l.seized = event.params.seized;
  l.blockNumber = event.block.number;
  l.timestamp = event.block.timestamp;
  l.txHash = event.transaction.hash;
  l.save();
}

export function handleBadDebtRealized(event: BadDebtRealized): void {
  let b = new VaultBadDebt(eventId(event));
  b.vault = event.address;
  b.borrower = event.params.borrower;
  b.amount = event.params.amount;
  b.blockNumber = event.block.number;
  b.timestamp = event.block.timestamp;
  b.txHash = event.transaction.hash;
  b.save();
}

export function handleWithdrawn(event: Withdrawn): void {
  let w = new VaultWithdrawal(eventId(event));
  w.vault = event.address;
  w.to = event.params.to;
  w.amount = event.params.amount;
  w.blockNumber = event.block.number;
  w.timestamp = event.block.timestamp;
  w.txHash = event.transaction.hash;
  w.save();
}

export function handleBuybackQueued(event: BuybackQueued): void {
  let b = new VaultBuybackQueued(eventId(event));
  b.vault = event.address;
  b.amount = event.params.amount;
  b.blockNumber = event.block.number;
  b.timestamp = event.block.timestamp;
  b.txHash = event.transaction.hash;
  b.save();
}

export function handleBuybackExecuted(event: BuybackExecuted): void {
  let b = new VaultBuybackExecuted(eventId(event));
  b.vault = event.address;
  b.currencyIn = event.params.currencyIn;
  b.tokensBurned = event.params.tokensBurned;
  b.blockNumber = event.block.number;
  b.timestamp = event.block.timestamp;
  b.txHash = event.transaction.hash;
  b.save();
}

export function handleEnabled(event: Enabled): void {
  let v = Vault.load(event.address);
  if (v == null) return;
  v.enabled = event.params.enabled;
  v.save();
}

export function handlePoolLinked(event: PoolLinked): void {
  let v = Vault.load(event.address);
  if (v == null) return;
  v.currency = event.params.currency;
  v.poolId = event.params.poolId;
  v.save();
}

export function handleGovernorSet(event: GovernorSet): void {
  let v = Vault.load(event.address);
  if (v != null) {
    v.governor = event.params.governor;
    v.save();
  }
  logAdminEvent(event, CONTRACT, "GovernorSet", event.params.governor.toHexString());
}

export function handleCreatorSet(event: CreatorSet): void {
  let v = Vault.load(event.address);
  if (v != null) {
    v.creator = event.params.creator;
    v.save();
  }
  logAdminEvent(event, CONTRACT, "CreatorSet", event.params.creator.toHexString());
}

// ---- config and admin events, recorded as AdminEvent ----

export function handleInitialized(event: Initialized): void {
  logAdminEvent(event, CONTRACT, "Initialized", event.params.version.toString());
}

export function handleRouteSucceeded(event: RouteSucceeded): void {
  logAdminEvent(event, CONTRACT, "RouteSucceeded", event.params.quoteToken.toHexString(), event.params.routeIndex.toString(), event.params.amountOut.toString());
}

export function handleRoutesSet(event: RoutesSet): void {
  logAdminEvent(event, CONTRACT, "RoutesSet", event.params.quoteToken.toHexString(), event.params.count.toString());
}

export function handleUniversalRouterUpdated(event: UniversalRouterUpdated): void {
  logAdminEvent(event, CONTRACT, "UniversalRouterUpdated", event.params.router.toHexString());
}

export function handleUpgraded(event: Upgraded): void {
  logAdminEvent(event, CONTRACT, "Upgraded", event.params.implementation.toHexString());
}
