// DuckVaultConfig event handlers. Generated by gen_subgraphs.py; edit the generator, not this file.
import {
  BuybackBpsUpdated,
  CloseFactorUpdated,
  Initialized,
  InterestCurveUpdated,
  LiquidationBonusUpdated,
  LiquidationThresholdUpdated,
  MaxBorrowerShareUpdated,
  MaxCirculatingShareUpdated,
  MaxLtvUpdated,
  MaxPoolDepthShareUpdated,
  MaxUtilizationUpdated,
  MinLoanUpdated,
  MinPoolAgeUpdated,
  OracleWindowsUpdated,
  OwnershipTransferStarted,
  OwnershipTransferred,
  Upgraded,
} from "../generated/DuckVaultConfig/DuckVaultConfig";
import { logAdminEvent, boolToString } from "./admin";

const CONTRACT = "DuckVaultConfig";

// ---- config and admin events, recorded as AdminEvent ----

export function handleBuybackBpsUpdated(event: BuybackBpsUpdated): void {
  logAdminEvent(event, CONTRACT, "BuybackBpsUpdated", event.params.bps.toString());
}

export function handleCloseFactorUpdated(event: CloseFactorUpdated): void {
  logAdminEvent(event, CONTRACT, "CloseFactorUpdated", event.params.bps.toString());
}

export function handleInitialized(event: Initialized): void {
  logAdminEvent(event, CONTRACT, "Initialized", event.params.version.toString());
}

export function handleInterestCurveUpdated(event: InterestCurveUpdated): void {
  logAdminEvent(event, CONTRACT, "InterestCurveUpdated", event.params.kinkBps.toString(), event.params.baseRateBps.toString(), event.params.slope1Bps.toString(), event.params.slope2Bps.toString());
}

export function handleLiquidationBonusUpdated(event: LiquidationBonusUpdated): void {
  logAdminEvent(event, CONTRACT, "LiquidationBonusUpdated", event.params.bps.toString());
}

export function handleLiquidationThresholdUpdated(event: LiquidationThresholdUpdated): void {
  logAdminEvent(event, CONTRACT, "LiquidationThresholdUpdated", event.params.bps.toString());
}

export function handleMaxBorrowerShareUpdated(event: MaxBorrowerShareUpdated): void {
  logAdminEvent(event, CONTRACT, "MaxBorrowerShareUpdated", event.params.bps.toString());
}

export function handleMaxCirculatingShareUpdated(event: MaxCirculatingShareUpdated): void {
  logAdminEvent(event, CONTRACT, "MaxCirculatingShareUpdated", event.params.bps.toString());
}

export function handleMaxLtvUpdated(event: MaxLtvUpdated): void {
  logAdminEvent(event, CONTRACT, "MaxLtvUpdated", event.params.bps.toString());
}

export function handleMaxPoolDepthShareUpdated(event: MaxPoolDepthShareUpdated): void {
  logAdminEvent(event, CONTRACT, "MaxPoolDepthShareUpdated", event.params.bps.toString());
}

export function handleMaxUtilizationUpdated(event: MaxUtilizationUpdated): void {
  logAdminEvent(event, CONTRACT, "MaxUtilizationUpdated", event.params.bps.toString());
}

export function handleMinLoanUpdated(event: MinLoanUpdated): void {
  logAdminEvent(event, CONTRACT, "MinLoanUpdated", event.params.currency.toHexString(), event.params.amount.toString());
}

export function handleMinPoolAgeUpdated(event: MinPoolAgeUpdated): void {
  logAdminEvent(event, CONTRACT, "MinPoolAgeUpdated", event.params.seconds_.toString());
}

export function handleOracleWindowsUpdated(event: OracleWindowsUpdated): void {
  logAdminEvent(event, CONTRACT, "OracleWindowsUpdated", event.params.shortWindow.toString(), event.params.longWindow.toString());
}

export function handleOwnershipTransferStarted(event: OwnershipTransferStarted): void {
  logAdminEvent(event, CONTRACT, "OwnershipTransferStarted", event.params.previousOwner.toHexString(), event.params.newOwner.toHexString());
}

export function handleOwnershipTransferred(event: OwnershipTransferred): void {
  logAdminEvent(event, CONTRACT, "OwnershipTransferred", event.params.previousOwner.toHexString(), event.params.newOwner.toHexString());
}

export function handleUpgraded(event: Upgraded): void {
  logAdminEvent(event, CONTRACT, "Upgraded", event.params.implementation.toHexString());
}
