// TimelockControllerUpgradeable event handlers. Generated by gen_subgraphs.py; edit the generator, not this file.
import {
  CallExecuted,
  CallSalt,
  CallScheduled,
  Cancelled,
  Initialized,
  MinDelayChange,
  RoleAdminChanged,
  RoleGranted,
  RoleRevoked,
} from "../generated/templates/TimelockControllerUpgradeable/TimelockControllerUpgradeable";
import { TimelockOperation } from "../generated/schema";
import { logAdminEvent, boolToString } from "./admin";

const CONTRACT = "TimelockControllerUpgradeable";

function operationEntityId(timelock: string, operationId: string, index: string): string {
  return timelock + "-" + operationId + "-" + index;
}

export function handleCallScheduled(event: CallScheduled): void {
  let op = new TimelockOperation(operationEntityId(event.address.toHexString(), event.params.id.toHexString(), event.params.index.toString()));
  op.timelock = event.address;
  op.operationId = event.params.id;
  op.index = event.params.index;
  op.target = event.params.target;
  op.value = event.params.value;
  op.data = event.params.data;
  op.predecessor = event.params.predecessor;
  op.delay = event.params.delay;
  op.executed = false;
  op.cancelled = false;
  op.scheduledAtBlock = event.block.number;
  op.scheduledAtTimestamp = event.block.timestamp;
  op.scheduledAtTx = event.transaction.hash;
  op.save();
}

export function handleCallExecuted(event: CallExecuted): void {
  let op = TimelockOperation.load(operationEntityId(event.address.toHexString(), event.params.id.toHexString(), event.params.index.toString()));
  if (op == null) return;
  op.executed = true;
  op.executedAtBlock = event.block.number;
  op.executedAtTimestamp = event.block.timestamp;
  op.executedAtTx = event.transaction.hash;
  op.save();
}

// Cancelled carries only the operation id. DuckTokenGovernor schedules single-call operations, so the
// call to mark is index 0.
export function handleCancelled(event: Cancelled): void {
  let op = TimelockOperation.load(operationEntityId(event.address.toHexString(), event.params.id.toHexString(), "0"));
  if (op != null) {
    op.cancelled = true;
    op.save();
  }
  logAdminEvent(event, CONTRACT, "Cancelled", event.params.id.toHexString());
}

// ---- config and admin events, recorded as AdminEvent ----

export function handleCallSalt(event: CallSalt): void {
  logAdminEvent(event, CONTRACT, "CallSalt", event.params.id.toHexString(), event.params.salt.toHexString());
}

export function handleInitialized(event: Initialized): void {
  logAdminEvent(event, CONTRACT, "Initialized", event.params.version.toString());
}

export function handleMinDelayChange(event: MinDelayChange): void {
  logAdminEvent(event, CONTRACT, "MinDelayChange", event.params.oldDuration.toString(), event.params.newDuration.toString());
}

export function handleRoleAdminChanged(event: RoleAdminChanged): void {
  logAdminEvent(event, CONTRACT, "RoleAdminChanged", event.params.role.toHexString(), event.params.previousAdminRole.toHexString(), event.params.newAdminRole.toHexString());
}

export function handleRoleGranted(event: RoleGranted): void {
  logAdminEvent(event, CONTRACT, "RoleGranted", event.params.role.toHexString(), event.params.account.toHexString(), event.params.sender.toHexString());
}

export function handleRoleRevoked(event: RoleRevoked): void {
  logAdminEvent(event, CONTRACT, "RoleRevoked", event.params.role.toHexString(), event.params.account.toHexString(), event.params.sender.toHexString());
}
