// DuckBondingCurve event handlers. Generated by gen_subgraphs.py; edit the generator, not this file.
import {
  AllocationBoundsUpdated,
  CreationFeeUpdated,
  CurveFeeClaimed,
  DexConfigUpdated,
  ETHRescued,
  EmergencyMigrated,
  FeeSplitsUpdated,
  ImplUpdated,
  Initialized,
  MigrationFailed,
  OwnershipTransferStarted,
  OwnershipTransferred,
  PlatformTokenUpdated,
  PlatformWalletUpdated,
  QuoteTokenUpdated,
  RouteSucceeded,
  RoutesSet,
  TokenBought,
  TokenCreated,
  TokenMigrated,
  TokenRegistered,
  TokenRescued,
  TokenSold,
  UniversalRouterUpdated,
  Upgraded,
} from "../generated/DuckBondingCurve/DuckBondingCurve";
import { BigInt } from "@graphprotocol/graph-ts";
import { Token, Trade, Migration, EmergencyMigration, MigrationFailure, CurveFeeClaim } from "../generated/schema";
import { DuckToken as DuckTokenTemplate } from "../generated/templates";
import { eventId } from "./admin";
import { newToken } from "./token-meta";
import { recordTrade } from "./normalize";
import { logAdminEvent, boolToString } from "./admin";

const CONTRACT = "DuckBondingCurve";

export function handleTokenRegistered(event: TokenRegistered): void {
  let t = newToken(event.params.token, "BondingCurve", event.params.creator, event.params.quoteToken, event);
  t.totalSupply = event.params.totalSupply;
  t.virtualQuote = event.params.virtualQuote;
  t.migrationTarget = event.params.migrationTarget;
  t.raisedQuote = BigInt.zero();
  t.bcTokensSold = BigInt.zero();
  t.save();
}

// TokenCreated follows TokenRegistered in the same createToken call. Starting the token template
// only here gives each token exactly one dynamic data source (a second would double-count holders).
export function handleTokenCreated(event: TokenCreated): void {
  DuckTokenTemplate.create(event.params.token);
  logAdminEvent(event, CONTRACT, "TokenCreated", event.params.token.toHexString(), event.params.creator.toHexString(), event.params.totalSupply.toString());
}

export function handleTokenBought(event: TokenBought): void {
  let tr = new Trade(eventId(event));
  tr.token = event.params.token;
  tr.trader = event.params.buyer;
  tr.isBuy = true;
  tr.quoteAmount = event.params.quoteIn;
  tr.tokenAmount = event.params.tokensOut;
  tr.raisedQuote = event.params.raisedQuote;
  tr.blockNumber = event.block.number;
  tr.timestamp = event.block.timestamp;
  tr.txHash = event.transaction.hash;

  let t = Token.load(event.params.token);
  if (t != null) {
    t.raisedQuote = event.params.raisedQuote;
    t.bcTokensSold = t.bcTokensSold!.plus(event.params.tokensOut);
    let value = recordTrade(t, event, event.params.quoteIn, event.params.tokensOut);
    tr.priceUSD = value.priceUSD;
    tr.volumeUSD = value.volumeUSD;
  }
  tr.save();
}

export function handleTokenSold(event: TokenSold): void {
  let tr = new Trade(eventId(event));
  tr.token = event.params.token;
  tr.trader = event.params.seller;
  tr.isBuy = false;
  tr.quoteAmount = event.params.quoteOut;
  tr.tokenAmount = event.params.tokensIn;
  tr.raisedQuote = event.params.raisedQuote;
  tr.blockNumber = event.block.number;
  tr.timestamp = event.block.timestamp;
  tr.txHash = event.transaction.hash;

  let t = Token.load(event.params.token);
  if (t != null) {
    t.raisedQuote = event.params.raisedQuote;
    t.bcTokensSold = t.bcTokensSold!.minus(event.params.tokensIn);
    let value = recordTrade(t, event, event.params.quoteOut, event.params.tokensIn);
    tr.priceUSD = value.priceUSD;
    tr.volumeUSD = value.volumeUSD;
  }
  tr.save();
}

export function handleTokenMigrated(event: TokenMigrated): void {
  let m = new Migration(eventId(event));
  m.token = event.params.token;
  m.poolId = event.params.poolId;
  m.liquidityQuote = event.params.liquidityQuote;
  m.liquidityTokens = event.params.liquidityTokens;
  m.blockNumber = event.block.number;
  m.timestamp = event.block.timestamp;
  m.txHash = event.transaction.hash;
  m.save();

  let t = Token.load(event.params.token);
  if (t == null) return;
  t.migrated = true;
  t.hasPool = true;
  t.poolId = event.params.poolId;
  t.save();
}

export function handleEmergencyMigrated(event: EmergencyMigrated): void {
  let m = new EmergencyMigration(eventId(event));
  m.token = event.params.token;
  m.to = event.params.to;
  m.quoteAmount = event.params.quoteAmount;
  m.tokenAmount = event.params.tokenAmount;
  m.blockNumber = event.block.number;
  m.timestamp = event.block.timestamp;
  m.txHash = event.transaction.hash;
  m.save();
}

export function handleMigrationFailed(event: MigrationFailed): void {
  let m = new MigrationFailure(eventId(event));
  m.token = event.params.token;
  m.blockNumber = event.block.number;
  m.timestamp = event.block.timestamp;
  m.txHash = event.transaction.hash;
  m.save();
}

export function handleCurveFeeClaimed(event: CurveFeeClaimed): void {
  let c = new CurveFeeClaim(eventId(event));
  c.token = event.params.token;
  c.creator = event.params.creator;
  c.creatorAmount = event.params.creatorAmount;
  c.platformAmount = event.params.platformAmount;
  c.blockNumber = event.block.number;
  c.timestamp = event.block.timestamp;
  c.txHash = event.transaction.hash;
  c.save();
}

// ---- config and admin events, recorded as AdminEvent ----

export function handleAllocationBoundsUpdated(event: AllocationBoundsUpdated): void {
  logAdminEvent(event, CONTRACT, "AllocationBoundsUpdated", event.params.minCurveBps.toString(), event.params.minLiquidityBps.toString());
}

export function handleCreationFeeUpdated(event: CreationFeeUpdated): void {
  logAdminEvent(event, CONTRACT, "CreationFeeUpdated", event.params.oldFee.toString(), event.params.newFee.toString());
}

export function handleDexConfigUpdated(event: DexConfigUpdated): void {
  logAdminEvent(event, CONTRACT, "DexConfigUpdated", event.params.positionManager.toHexString(), event.params.singleton.toHexString(), event.params.hook.toHexString());
}

export function handleETHRescued(event: ETHRescued): void {
  logAdminEvent(event, CONTRACT, "ETHRescued", event.params.to.toHexString(), event.params.amount.toString());
}

export function handleFeeSplitsUpdated(event: FeeSplitsUpdated): void {
  logAdminEvent(event, CONTRACT, "FeeSplitsUpdated", event.params.token.toHexString(), event.params.splits.length.toString());
}

export function handleImplUpdated(event: ImplUpdated): void {
  logAdminEvent(event, CONTRACT, "ImplUpdated", event.params.implType, event.params.prev.toHexString(), event.params.next.toHexString());
}

export function handleInitialized(event: Initialized): void {
  logAdminEvent(event, CONTRACT, "Initialized", event.params.version.toString());
}

export function handleOwnershipTransferStarted(event: OwnershipTransferStarted): void {
  logAdminEvent(event, CONTRACT, "OwnershipTransferStarted", event.params.previousOwner.toHexString(), event.params.newOwner.toHexString());
}

export function handleOwnershipTransferred(event: OwnershipTransferred): void {
  logAdminEvent(event, CONTRACT, "OwnershipTransferred", event.params.previousOwner.toHexString(), event.params.newOwner.toHexString());
}

export function handlePlatformTokenUpdated(event: PlatformTokenUpdated): void {
  logAdminEvent(event, CONTRACT, "PlatformTokenUpdated", event.params.token.toHexString());
}

export function handlePlatformWalletUpdated(event: PlatformWalletUpdated): void {
  logAdminEvent(event, CONTRACT, "PlatformWalletUpdated", event.params.recipient.toHexString());
}

export function handleQuoteTokenUpdated(event: QuoteTokenUpdated): void {
  logAdminEvent(event, CONTRACT, "QuoteTokenUpdated", event.params.token.toHexString(), boolToString(event.params.allowed));
}

export function handleRouteSucceeded(event: RouteSucceeded): void {
  logAdminEvent(event, CONTRACT, "RouteSucceeded", event.params.quoteToken.toHexString(), event.params.routeIndex.toString(), event.params.amountOut.toString());
}

export function handleRoutesSet(event: RoutesSet): void {
  logAdminEvent(event, CONTRACT, "RoutesSet", event.params.quoteToken.toHexString(), event.params.count.toString());
}

export function handleTokenRescued(event: TokenRescued): void {
  logAdminEvent(event, CONTRACT, "TokenRescued", event.params.token.toHexString(), event.params.to.toHexString(), event.params.amount.toString());
}

export function handleUniversalRouterUpdated(event: UniversalRouterUpdated): void {
  logAdminEvent(event, CONTRACT, "UniversalRouterUpdated", event.params.router.toHexString());
}

export function handleUpgraded(event: Upgraded): void {
  logAdminEvent(event, CONTRACT, "Upgraded", event.params.implementation.toHexString());
}
