// DuckCrowdfund event handlers. Generated by gen_subgraphs.py; edit the generator, not this file.
import {
  CampaignCreated,
  CampaignDurationSet,
  CampaignFailed,
  CampaignFeeSet,
  CampaignSucceeded,
  Claimed,
  Contributed,
  DexConfigSet,
  Initialized,
  OwnershipTransferStarted,
  OwnershipTransferred,
  PlatformTokenSet,
  PlatformWalletSet,
  QuoteAssetUpdated,
  Refunded,
  RouteSucceeded,
  RoutesSet,
  SupplySplitSet,
  TokenImplSet,
  UniversalRouterUpdated,
  Upgraded,
  VaultFactorySet,
  WethSet,
} from "../generated/DuckCrowdfund/DuckCrowdfund";
import { Address, BigInt } from "@graphprotocol/graph-ts";
import { DuckCrowdfund } from "../generated/DuckCrowdfund/DuckCrowdfund";
import { Campaign, Contribution, Claim, Refund } from "../generated/schema";
import { DuckToken as DuckTokenTemplate } from "../generated/templates";
import { eventId } from "./admin";
import { newToken } from "./token-meta";
import { logAdminEvent, boolToString } from "./admin";

const CONTRACT = "DuckCrowdfund";

function campaignEntityId(crowdfund: Address, campaignId: BigInt): string {
  return crowdfund.toHexString() + "-" + campaignId.toString();
}

export function handleCampaignCreated(event: CampaignCreated): void {
  let t = newToken(event.params.token, "Crowdfund", event.params.creator, event.params.dexQuoteAsset, event);
  if (t.name == null) t.name = event.params.name;
  if (t.symbol == null) t.symbol = event.params.symbol;

  let c = new Campaign(campaignEntityId(event.address, event.params.campaignId));
  c.campaignId = event.params.campaignId;
  c.creator = event.params.creator;
  c.token = event.params.token;
  c.name = event.params.name;
  c.symbol = event.params.symbol;
  c.dexQuoteAsset = event.params.dexQuoteAsset;
  c.goal = event.params.goal;
  c.startTime = event.params.startTime;
  c.deadline = event.params.deadline;
  c.totalRaised = BigInt.zero();
  c.finalized = false;
  c.succeeded = false;
  let meta = DuckCrowdfund.bind(event.address).try_getCampaignMeta(event.params.campaignId);
  if (!meta.reverted) {
    c.metaUri = meta.value.getMetaURI();
    c.totalSupply = meta.value.getTotalSupply();
    c.contributorBps = meta.value.getContributorBps();
    c.lpBps = meta.value.getLpBps();
    c.hookFeeBps = meta.value.getHookFeeBps();
    c.vaultBps = meta.value.getVaultBps();
    t.totalSupply = meta.value.getTotalSupply();
    if (t.metaUri == null) t.metaUri = meta.value.getMetaURI();
  }
  c.createdAtBlock = event.block.number;
  c.createdAtTimestamp = event.block.timestamp;
  c.createdAtTx = event.transaction.hash;
  c.save();
  t.save();

  DuckTokenTemplate.create(event.params.token);
}

export function handleContributed(event: Contributed): void {
  let id = campaignEntityId(event.address, event.params.campaignId);
  let c = Campaign.load(id);
  if (c != null) {
    c.totalRaised = c.totalRaised.plus(event.params.amount);
    c.save();
  }
  let x = new Contribution(eventId(event));
  x.campaign = id;
  x.contributor = event.params.contributor;
  x.amount = event.params.amount;
  x.blockNumber = event.block.number;
  x.timestamp = event.block.timestamp;
  x.txHash = event.transaction.hash;
  x.save();
}

export function handleCampaignSucceeded(event: CampaignSucceeded): void {
  let c = Campaign.load(campaignEntityId(event.address, event.params.campaignId));
  if (c == null) return;
  c.finalized = true;
  c.succeeded = true;
  c.totalRaised = event.params.totalRaised;
  c.save();
}

export function handleCampaignFailed(event: CampaignFailed): void {
  let c = Campaign.load(campaignEntityId(event.address, event.params.campaignId));
  if (c == null) return;
  c.finalized = true;
  c.succeeded = false;
  c.totalRaised = event.params.totalRaised;
  c.save();
}

export function handleClaimed(event: Claimed): void {
  let x = new Claim(eventId(event));
  x.campaign = campaignEntityId(event.address, event.params.campaignId);
  x.contributor = event.params.contributor;
  x.amount = event.params.amount;
  x.blockNumber = event.block.number;
  x.timestamp = event.block.timestamp;
  x.txHash = event.transaction.hash;
  x.save();
}

export function handleRefunded(event: Refunded): void {
  let x = new Refund(eventId(event));
  x.campaign = campaignEntityId(event.address, event.params.campaignId);
  x.contributor = event.params.contributor;
  x.amount = event.params.amount;
  x.blockNumber = event.block.number;
  x.timestamp = event.block.timestamp;
  x.txHash = event.transaction.hash;
  x.save();
}

// ---- config and admin events, recorded as AdminEvent ----

export function handleCampaignDurationSet(event: CampaignDurationSet): void {
  logAdminEvent(event, CONTRACT, "CampaignDurationSet", event.params.duration.toString());
}

export function handleCampaignFeeSet(event: CampaignFeeSet): void {
  logAdminEvent(event, CONTRACT, "CampaignFeeSet", event.params.fee.toString());
}

export function handleDexConfigSet(event: DexConfigSet): void {
  logAdminEvent(event, CONTRACT, "DexConfigSet", event.params.positionManager.toHexString(), event.params.singleton.toHexString(), event.params.hook.toHexString());
}

export function handleInitialized(event: Initialized): void {
  logAdminEvent(event, CONTRACT, "Initialized", event.params.version.toString());
}

export function handleOwnershipTransferStarted(event: OwnershipTransferStarted): void {
  logAdminEvent(event, CONTRACT, "OwnershipTransferStarted", event.params.previousOwner.toHexString(), event.params.newOwner.toHexString());
}

export function handleOwnershipTransferred(event: OwnershipTransferred): void {
  logAdminEvent(event, CONTRACT, "OwnershipTransferred", event.params.previousOwner.toHexString(), event.params.newOwner.toHexString());
}

export function handlePlatformTokenSet(event: PlatformTokenSet): void {
  logAdminEvent(event, CONTRACT, "PlatformTokenSet", event.params.token.toHexString());
}

export function handlePlatformWalletSet(event: PlatformWalletSet): void {
  logAdminEvent(event, CONTRACT, "PlatformWalletSet", event.params.wallet.toHexString());
}

export function handleQuoteAssetUpdated(event: QuoteAssetUpdated): void {
  logAdminEvent(event, CONTRACT, "QuoteAssetUpdated", event.params.token.toHexString(), boolToString(event.params.allowed));
}

export function handleRouteSucceeded(event: RouteSucceeded): void {
  logAdminEvent(event, CONTRACT, "RouteSucceeded", event.params.quoteToken.toHexString(), event.params.routeIndex.toString(), event.params.amountOut.toString());
}

export function handleRoutesSet(event: RoutesSet): void {
  logAdminEvent(event, CONTRACT, "RoutesSet", event.params.quoteToken.toHexString(), event.params.count.toString());
}

export function handleSupplySplitSet(event: SupplySplitSet): void {
  logAdminEvent(event, CONTRACT, "SupplySplitSet", event.params.contributorBps.toString(), event.params.lpBps.toString());
}

export function handleTokenImplSet(event: TokenImplSet): void {
  logAdminEvent(event, CONTRACT, "TokenImplSet", event.params.tokenImpl.toHexString());
}

export function handleUniversalRouterUpdated(event: UniversalRouterUpdated): void {
  logAdminEvent(event, CONTRACT, "UniversalRouterUpdated", event.params.router.toHexString());
}

export function handleUpgraded(event: Upgraded): void {
  logAdminEvent(event, CONTRACT, "Upgraded", event.params.implementation.toHexString());
}

export function handleVaultFactorySet(event: VaultFactorySet): void {
  logAdminEvent(event, CONTRACT, "VaultFactorySet", event.params.vaultFactory.toHexString());
}

export function handleWethSet(event: WethSet): void {
  logAdminEvent(event, CONTRACT, "WethSet", event.params.weth.toHexString());
}
