// DuckVaultFactory event handlers. Generated by gen_subgraphs.py; edit the generator, not this file.
import {
  ConfigSet,
  FamilySet,
  GovernorFactorySet,
  HookSet,
  Initialized,
  OwnershipTransferStarted,
  OwnershipTransferred,
  Upgraded,
  VaultCreated,
  VaultImplApproved,
  VaultImplRevoked,
  VaultImplSet,
} from "../generated/DuckVaultFactory/DuckVaultFactory";
import { Vault } from "../generated/schema";
import { DuckVault as DuckVaultTemplate } from "../generated/templates";
import { logAdminEvent, boolToString } from "./admin";

const CONTRACT = "DuckVaultFactory";

export function handleVaultCreated(event: VaultCreated): void {
  let v = new Vault(event.params.vault);
  v.token = event.params.token;
  v.family = event.params.family;
  v.creator = event.params.creator;
  v.enabled = false;
  v.createdAtBlock = event.block.number;
  v.createdAtTimestamp = event.block.timestamp;
  v.createdAtTx = event.transaction.hash;
  v.save();
  DuckVaultTemplate.create(event.params.vault);
}

// ---- config and admin events, recorded as AdminEvent ----

export function handleConfigSet(event: ConfigSet): void {
  logAdminEvent(event, CONTRACT, "ConfigSet", event.params.config.toHexString());
}

export function handleFamilySet(event: FamilySet): void {
  logAdminEvent(event, CONTRACT, "FamilySet", event.params.family.toHexString(), boolToString(event.params.allowed));
}

export function handleGovernorFactorySet(event: GovernorFactorySet): void {
  logAdminEvent(event, CONTRACT, "GovernorFactorySet", event.params.governorFactory.toHexString());
}

export function handleHookSet(event: HookSet): void {
  logAdminEvent(event, CONTRACT, "HookSet", event.params.hook.toHexString());
}

export function handleInitialized(event: Initialized): void {
  logAdminEvent(event, CONTRACT, "Initialized", event.params.version.toString());
}

export function handleOwnershipTransferStarted(event: OwnershipTransferStarted): void {
  logAdminEvent(event, CONTRACT, "OwnershipTransferStarted", event.params.previousOwner.toHexString(), event.params.newOwner.toHexString());
}

export function handleOwnershipTransferred(event: OwnershipTransferred): void {
  logAdminEvent(event, CONTRACT, "OwnershipTransferred", event.params.previousOwner.toHexString(), event.params.newOwner.toHexString());
}

export function handleUpgraded(event: Upgraded): void {
  logAdminEvent(event, CONTRACT, "Upgraded", event.params.implementation.toHexString());
}

export function handleVaultImplApproved(event: VaultImplApproved): void {
  logAdminEvent(event, CONTRACT, "VaultImplApproved", event.params.impl.toHexString());
}

export function handleVaultImplRevoked(event: VaultImplRevoked): void {
  logAdminEvent(event, CONTRACT, "VaultImplRevoked", event.params.impl.toHexString());
}

export function handleVaultImplSet(event: VaultImplSet): void {
  logAdminEvent(event, CONTRACT, "VaultImplSet", event.params.impl.toHexString());
}
