// DuckTokenGovernorFactory event handlers. Generated by gen_subgraphs.py; edit the generator, not this file.
import {
  DefaultVotingParamsSet,
  GovernorCreated,
  GovernorImplSet,
  Initialized,
  OwnershipTransferStarted,
  OwnershipTransferred,
  TimelockCreated,
  TimelockImplSet,
  Upgraded,
} from "../generated/DuckTokenGovernorFactory/DuckTokenGovernorFactory";
import { Governor, Timelock } from "../generated/schema";
import { DuckTokenGovernor as DuckTokenGovernorTemplate, TimelockControllerUpgradeable as TimelockTemplate } from "../generated/templates";
import { logAdminEvent, boolToString } from "./admin";

const CONTRACT = "DuckTokenGovernorFactory";

export function handleGovernorCreated(event: GovernorCreated): void {
  let g = new Governor(event.params.governor);
  g.vault = event.params.vault;
  g.creator = event.params.creator;
  g.createdAtBlock = event.block.number;
  g.createdAtTimestamp = event.block.timestamp;
  g.createdAtTx = event.transaction.hash;
  g.save();
  DuckTokenGovernorTemplate.create(event.params.governor);
}

export function handleTimelockCreated(event: TimelockCreated): void {
  let t = new Timelock(event.params.timelock);
  t.vault = event.params.vault;
  t.createdAtBlock = event.block.number;
  t.createdAtTimestamp = event.block.timestamp;
  t.createdAtTx = event.transaction.hash;
  t.save();
  TimelockTemplate.create(event.params.timelock);
}

// ---- config and admin events, recorded as AdminEvent ----

export function handleDefaultVotingParamsSet(event: DefaultVotingParamsSet): void {
  logAdminEvent(event, CONTRACT, "DefaultVotingParamsSet", event.params.votingDelay.toString(), event.params.votingPeriod.toString());
}

export function handleGovernorImplSet(event: GovernorImplSet): void {
  logAdminEvent(event, CONTRACT, "GovernorImplSet", event.params.impl.toHexString());
}

export function handleInitialized(event: Initialized): void {
  logAdminEvent(event, CONTRACT, "Initialized", event.params.version.toString());
}

export function handleOwnershipTransferStarted(event: OwnershipTransferStarted): void {
  logAdminEvent(event, CONTRACT, "OwnershipTransferStarted", event.params.previousOwner.toHexString(), event.params.newOwner.toHexString());
}

export function handleOwnershipTransferred(event: OwnershipTransferred): void {
  logAdminEvent(event, CONTRACT, "OwnershipTransferred", event.params.previousOwner.toHexString(), event.params.newOwner.toHexString());
}

export function handleTimelockImplSet(event: TimelockImplSet): void {
  logAdminEvent(event, CONTRACT, "TimelockImplSet", event.params.impl.toHexString());
}

export function handleUpgraded(event: Upgraded): void {
  logAdminEvent(event, CONTRACT, "Upgraded", event.params.implementation.toHexString());
}
