// DuckTokenGovernor event handlers. Generated by gen_subgraphs.py; edit the generator, not this file.
import {
  EIP712DomainChanged,
  Initialized,
  ProposalCanceled,
  ProposalCreated,
  ProposalExecuted,
  ProposalQueued,
  ProposalThresholdSet,
  TimelockChange,
  VoteCast,
  VoteCastWithParams,
  VotingDelaySet,
  VotingPeriodSet,
} from "../generated/templates/DuckTokenGovernor/DuckTokenGovernor";
import { Bytes } from "@graphprotocol/graph-ts";
import { Proposal, Vote } from "../generated/schema";
import { eventId } from "./admin";
import { logAdminEvent, boolToString } from "./admin";

const CONTRACT = "DuckTokenGovernor";

function proposalEntityId(governor: string, proposalId: string): string {
  return governor + "-" + proposalId;
}

export function handleProposalCreated(event: ProposalCreated): void {
  let p = new Proposal(proposalEntityId(event.address.toHexString(), event.params.proposalId.toString()));
  p.governor = event.address;
  p.proposalId = event.params.proposalId;
  p.proposer = event.params.proposer;
  p.targets = event.params.targets.map<Bytes>((a) => a as Bytes);
  p.values = event.params.values;
  p.signatures = event.params.signatures;
  p.calldatas = event.params.calldatas;
  p.voteStart = event.params.voteStart;
  p.voteEnd = event.params.voteEnd;
  p.description = event.params.description;
  p.canceled = false;
  p.queued = false;
  p.executed = false;
  p.createdAtBlock = event.block.number;
  p.createdAtTimestamp = event.block.timestamp;
  p.createdAtTx = event.transaction.hash;
  p.save();
}

export function handleProposalCanceled(event: ProposalCanceled): void {
  let p = Proposal.load(proposalEntityId(event.address.toHexString(), event.params.proposalId.toString()));
  if (p == null) return;
  p.canceled = true;
  p.save();
}

export function handleProposalQueued(event: ProposalQueued): void {
  let p = Proposal.load(proposalEntityId(event.address.toHexString(), event.params.proposalId.toString()));
  if (p == null) return;
  p.queued = true;
  p.etaSeconds = event.params.etaSeconds;
  p.save();
}

export function handleProposalExecuted(event: ProposalExecuted): void {
  let p = Proposal.load(proposalEntityId(event.address.toHexString(), event.params.proposalId.toString()));
  if (p == null) return;
  p.executed = true;
  p.save();
}

export function handleVoteCast(event: VoteCast): void {
  let v = new Vote(eventId(event));
  v.governor = event.address;
  v.proposal = proposalEntityId(event.address.toHexString(), event.params.proposalId.toString());
  v.voter = event.params.voter;
  v.support = event.params.support;
  v.weight = event.params.weight;
  v.reason = event.params.reason;
  v.blockNumber = event.block.number;
  v.timestamp = event.block.timestamp;
  v.txHash = event.transaction.hash;
  v.save();
}

export function handleVoteCastWithParams(event: VoteCastWithParams): void {
  let v = new Vote(eventId(event));
  v.governor = event.address;
  v.proposal = proposalEntityId(event.address.toHexString(), event.params.proposalId.toString());
  v.voter = event.params.voter;
  v.support = event.params.support;
  v.weight = event.params.weight;
  v.reason = event.params.reason;
  v.params = event.params.params;
  v.blockNumber = event.block.number;
  v.timestamp = event.block.timestamp;
  v.txHash = event.transaction.hash;
  v.save();
}

// ---- config and admin events, recorded as AdminEvent ----

export function handleEIP712DomainChanged(event: EIP712DomainChanged): void {
  logAdminEvent(event, CONTRACT, "EIP712DomainChanged");
}

export function handleInitialized(event: Initialized): void {
  logAdminEvent(event, CONTRACT, "Initialized", event.params.version.toString());
}

export function handleProposalThresholdSet(event: ProposalThresholdSet): void {
  logAdminEvent(event, CONTRACT, "ProposalThresholdSet", event.params.oldProposalThreshold.toString(), event.params.newProposalThreshold.toString());
}

export function handleTimelockChange(event: TimelockChange): void {
  logAdminEvent(event, CONTRACT, "TimelockChange", event.params.oldTimelock.toHexString(), event.params.newTimelock.toHexString());
}

export function handleVotingDelaySet(event: VotingDelaySet): void {
  logAdminEvent(event, CONTRACT, "VotingDelaySet", event.params.oldVotingDelay.toString(), event.params.newVotingDelay.toString());
}

export function handleVotingPeriodSet(event: VotingPeriodSet): void {
  logAdminEvent(event, CONTRACT, "VotingPeriodSet", event.params.oldVotingPeriod.toString(), event.params.newVotingPeriod.toString());
}
