// PoolManager event handlers. Generated by gen_subgraphs.py; edit the generator, not this file.
import {
  Swap,
} from "../generated/PoolManager/PoolManager";
import { BigInt } from "@graphprotocol/graph-ts";
import { PoolRegistration, PoolSwap, Token } from "../generated/schema";
import { eventId } from "./admin";
import { recordTrade } from "./normalize";
import { findV4RefPool, recordV4ReferenceSwap } from "./pricing";

const NATIVE_HEX = "0x0000000000000000000000000000000000000000";
import { logAdminEvent, boolToString } from "./admin";

const CONTRACT = "PoolManager";

// The PoolManager is the chain-wide v4 singleton, so it emits Swap for every pool. Only pools the
// hook registered belong to DuckProtocol; everything else is skipped.
export function handleSwap(event: Swap): void {
  let ref = findV4RefPool(event.params.id);
  if (ref != null) {
    recordV4ReferenceSwap(ref, event.params.sqrtPriceX96, event.params.liquidity, event);
  }

  let reg = PoolRegistration.load(event.params.id);
  if (reg == null) return;
  let t = Token.load(reg.token);
  if (t == null) return;

  let quoteHex = t.quoteToken !== null ? t.quoteToken!.toHexString() : NATIVE_HEX;
  let tokenIsCurrency0 = t.id.toHexString() < quoteHex; // v4 sorts currencies by address
  let tokenDelta = tokenIsCurrency0 ? event.params.amount0 : event.params.amount1;
  let quoteDelta = tokenIsCurrency0 ? event.params.amount1 : event.params.amount0;

  // Deltas are from the swapper's side: a positive token delta means the swapper received the token.
  let isBuy = tokenDelta.gt(BigInt.zero());
  let tokenAmount = tokenDelta.lt(BigInt.zero()) ? tokenDelta.neg() : tokenDelta;
  let quoteAmount = quoteDelta.lt(BigInt.zero()) ? quoteDelta.neg() : quoteDelta;
  let value = recordTrade(t, event, quoteAmount, tokenAmount);

  let s = new PoolSwap(eventId(event));
  s.token = t.id;
  // event.params.sender is the router that called PoolManager; the signing wallet is the trader.
  s.trader = event.transaction.from;
  s.isBuy = isBuy;
  s.quoteAmount = quoteAmount;
  s.tokenAmount = tokenAmount;
  s.priceUSD = value.priceUSD;
  s.volumeUSD = value.volumeUSD;
  s.blockNumber = event.block.number;
  s.timestamp = event.block.timestamp;
  s.txHash = event.transaction.hash;
  s.save();
}
