// USD price reference config for every network. Generated by gen_subgraphs.py.
export const KIND_ETH_STABLE: i32 = 0;
export const KIND_TOKEN_ETH: i32 = 1;
export const KIND_TOKEN_STABLE: i32 = 2;

export class RefPool {
  pool: string;
  token: string;
  kind: i32;
  pricedIsToken0: boolean;
  dec0: i32;
  dec1: i32;
  discovered: boolean = false;
  constructor(pool: string, token: string, kind: i32, pricedIsToken0: boolean, dec0: i32, dec1: i32) {
    this.pool = pool;
    this.token = token;
    this.kind = kind;
    this.pricedIsToken0 = pricedIsToken0;
    this.dec0 = dec0;
    this.dec1 = dec1;
  }
}

export class V4RefPool {
  poolId: string;
  token: string;
  tokenDecimals: i32;
  discovered: boolean = false;
  constructor(poolId: string, token: string, tokenDecimals: i32) {
    this.poolId = poolId;
    this.token = token;
    this.tokenDecimals = tokenDecimals;
  }
}

export function refPools(network: string): RefPool[] {
  if (network == "ink") return [
    new RefPool("0x356667da30c89cc36c65d394500424d5eba8731c", "0x4200000000000000000000000000000000000006", KIND_ETH_STABLE, false, 6, 18), // ETH
    new RefPool("0x5a56ff4b88f0ff5b33d4b0cf541fe76daf343e46", "0x4200000000000000000000000000000000000006", KIND_ETH_STABLE, true, 18, 6), // ETH
    new RefPool("0x6ab98b2e11a3cadb7021c390b9011b6a7c03cdfe", "0x73e0c0d45e048d25fc26fa3159b0aa04bfa4db98", KIND_TOKEN_STABLE, false, 6, 8), // BTC
    new RefPool("0x01951ddb43a451500bfaf652d40c07309fad4727", "0xa8ddb5cd96b5222afe198316e9a57caa642850d5", KIND_TOKEN_STABLE, true, 18, 6), // NVDAw
    new RefPool("0x169f2ab4d25aba4f9b2743658f8549641c9d069d", "0x30987adf0b11dc698438a99ba04ec3a1ab2c7eab", KIND_TOKEN_STABLE, true, 18, 6), // MSTRw
    new RefPool("0x06fb000fe9c6505eb3b2cdf52445d8c7d5690f47", "0xe7e553cd128f0011777323a0b44a7b96ea1cb540", KIND_TOKEN_STABLE, false, 6, 18), // SPYw
    new RefPool("0xdf1531451f6d97f847b27fac671738d113db1406", "0x8e2eed8b8b5e13ea7bf38e50d7821d2c57309072", KIND_TOKEN_STABLE, true, 18, 6), // SPCXw
    new RefPool("0x8986bb68391ad5b0afd7605e8075b273ca0189d6", "0x943bf64d566c32a2bcd41ac92fb63c111cc9de8f", KIND_TOKEN_STABLE, true, 18, 6), // AAPLw
    new RefPool("0x111d25ac72ad434d895f6f1ac8184ab5175e99ff", "0x7d87fd6a379714194a797c0bbb8b40c30d250856", KIND_TOKEN_STABLE, true, 18, 6), // NFLXw
    new RefPool("0x09444cbdff5cd4437150a1f26865a3ed85d8ed5e", "0xc3fdbe3a68ee5de461d30415a8165cf9aefe1171", KIND_TOKEN_STABLE, true, 18, 6), // TSLAw
  ];
  if (network == "robinhood-mainnet") return [
    new RefPool("0xd30e44aae604b42a63f6f9a8109fd0408f35b9fb", "0xcec185eb182c47d1ba1efc84e6959e18cd620be4", KIND_TOKEN_ETH, false, 18, 8), // BTC
    new RefPool("0x572d51a3de7c220fdd19451e4e24183b9f2ecadc", "0xf3081494b87e8d5fb7960f066e931d1d0e6e3d67", KIND_TOKEN_ETH, false, 18, 18), // TAO
    new RefPool("0xddcbba3666f578e3f09516f21ff85bfee859ab5e", "0x117cc2133c37b721f49de2a7a74833232b3b4c0c", KIND_TOKEN_ETH, false, 18, 18), // SPY
    new RefPool("0x62ab521f71431f78ac374cdbadc6cda3c8916b6c", "0xd0601ce157db5bdc3162bbac2a2c8af5320d9eec", KIND_TOKEN_ETH, false, 18, 18), // NVDA
    new RefPool("0xc3c9f0171490ef0f4536fe493f3b0ebb5ee0cb5e", "0x4a0e65a3eccec6dbe60ae065f2e7bb85fae35eea", KIND_TOKEN_ETH, false, 18, 18), // SPCX
    new RefPool("0x8bb3514e2204e1cdf3ac149efee7ff04d91b719f", "0xaf3d76f1834a1d425780943c99ea8a608f8a93f9", KIND_TOKEN_ETH, false, 18, 18), // AAPL
    new RefPool("0xa953ca88ff430e9487c60ca34d757414f4efda07", "0x322f0929c4625ed5bad873c95208d54e1c003b2d", KIND_TOKEN_ETH, false, 18, 18), // TSLA
    new RefPool("0x98996e833ea35ec17c3645ca7b6dd40d188564c4", "0xc9a981fee1f9dec688bb123ccdecc63d0debfc4e", KIND_TOKEN_ETH, false, 18, 18), // GLD
    new RefPool("0x70504a6fafdbfb75fe971faa4dd716e79ac5624c", "0xec262a75e413fafd0df80480274532c79d42da09", KIND_TOKEN_ETH, false, 18, 18), // MSTR
    new RefPool("0xc6bcc95043dc48c204bb2d57fb264a10efe0a607", "0x1b0e319c6a659f002271b69db8a7df2f911c153e", KIND_TOKEN_ETH, false, 18, 18), // GME
    new RefPool("0x34d0dc122cf9a8eb296fc5e0d3a233625d7d19b7", "0x2e0847e8910a9732eb3fb1bb4b70a580adad4fe3", KIND_TOKEN_STABLE, true, 18, 6), // GOOGL
    new RefPool("0x8ac92da74ab5f3b1d024dc1943ad7e15dc4179ef", "0x12f190a9f9d7d37a250758b26824b97ce941bf54", KIND_TOKEN_STABLE, true, 18, 6), // AMZN
    new RefPool("0xeb60bcd1d920ad6e102690ccfc6fb488899e1510", "0xe93237c50d904957cf27e7b1133b510c669c2e74", KIND_TOKEN_STABLE, false, 6, 18), // MSFT
    new RefPool("0x52e65b17fb6e5ba00ed806f37afcd2daa50271ca", "0x0bd7d308f8e1639fab988df18a8011f41eacad73", KIND_ETH_STABLE, true, 18, 6), // ETH
  ];
  return new Array<RefPool>(0);
}

export function v4RefPools(network: string): V4RefPool[] {
  if (network == "robinhood-mainnet") return [
    new V4RefPool("0x7ba2c8a5f53ee4cda9ef07effe81bb8509efafb79a26d0e33b28ada879e5bb52", "0xd5f3879160bc7c32ebb4dc785f8a4f505888de68", 18), // QQQ
  ];
  return new Array<V4RefPool>(0);
}

export function stableTokens(network: string): string[] {
  if (network == "robinhood-mainnet") return ["0x5fc5360d0400a0fd4f2af552add042d716f1d168", "0xce24439f2d9c6a2289f741120fe202248b666666"];
  if (network == "ink") return ["0x0200c29006150606b650577bbe7b6248f58470c1", "0xf1815bd50389c46847f0bda824ec8da914045d14", "0xe343167631d89b6ffc58b88d6b7fb0228795491d"];
  return new Array<string>(0);
}

export function wrappedNative(network: string): string {
  if (network == "robinhood-mainnet") return "0x0bd7d308f8e1639fab988df18a8011f41eacad73";
  if (network == "ink") return "0x4200000000000000000000000000000000000006";
  return "";
}

export function v3Factory(network: string): string {
  if (network == "robinhood-mainnet") return "0x1f7d7550b1b028f7571e69a784071f0205fd2efa";
  if (network == "ink") return "0x640887a9ba3a9c53ed27d0f7e8246a4f933f3424";
  return "";
}

export function v4PoolManager(network: string): string {
  if (network == "robinhood-mainnet") return "0x8366a39cc670b4001a1121b8f6a443a643e40951";
  if (network == "ink") return "0x360e68faccca8ca495c1b759fd9eee466db9fb32";
  return "";
}
